### ISSUE TITLE
this shit is insane

### ISSUE THREAD

**Issue by binnichtaktiv** [qtchaos/py_mega_account_generator#1]
Hi bro
I have no issue I just wanted to say that this is awesome. Keep it up 
Btw can I create unlimited Accounts with this script?

**Comment by qtchaos** [comment]
Thanks! And answering your question: sure, until your IP gets blocked by mega.nz (hasn't happened to me.)

**Comment by binnichtaktiv** [comment]
> Thanks! And answering your question: sure, until your IP gets blocked by mega.nz (hasn't happened to me.)

okay👍🏻 but i can bypass this with vpn or not? I think you can?

**Comment by qtchaos** [comment]
> > Thanks! And answering your question: sure, until your IP gets blocked by mega.nz (hasn't happened to me.)
> 
> okay👍🏻 but i can bypass this with vpn or not? I think you can?

You probably would be able to, yes.
