### ISSUE TITLE
hi I wanted to ask because an error occurred.

### ISSUE THREAD

**Issue by awdwadwadwad12345** [qtchaos/py_mega_account_generator#10]
![image](https://github.com/qtchaos/py_mega_account_generator/assets/146379307/38f1170d-2243-46f6-9b27-723055fb0bc8)

**Comment by qtchaos** [comment]
Were you creating a lot of accounts at a time?

**Comment by qtchaos** [comment]
Fixed with 41493c4e207521c380d863408bc7f897b47a0c58.
