### ISSUE TITLE
#freeStart timeout error.

### ISSUE THREAD

**Issue by DogancanYr** [qtchaos/py_mega_account_generator#15]
```
Killed previous instances successfully!
Registered account successfully!
Retrieved mail successfully!
Found mail!
Traceback (most recent call last):
  File "C:\Users\Dogan\Desktop\py_mega_account_generator-master\main.py", line 138, in <module>
    asyncio.run(register(asyncio.run(generate_mail())))
  File "C:\Users\Dogan\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Dogan\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\Dogan\Desktop\py_mega_account_generator-master\main.py", line 76, in register
    await initial_setup(context, message, credentials)
  File "C:\Users\Dogan\Desktop\py_mega_account_generator-master\utilities\web.py", line 43, in initial_setup
    await confirm_page.waitForSelector("#freeStart", timeout=1000)
  File "C:\Users\Dogan\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\frame_manager.py", line 855, in __await__
    raise result
pyppeteer.errors.TimeoutError: Waiting for selector "#freeStart" failed: timeout 1000ms exceeds.
```

**Comment by qtchaos** [comment]
Wait a bit before trying again, works for me.

**Comment by DogancanYr** [comment]
```
Failed to clear temporary files... killing previous instances.
Killing process msedgewebview2.exe...
Killing process msedgewebview2.exe...
Killed previous instances successfully!
Failed to clear temporary files... killing previous instances.
Killed previous instances successfully!
Retrying mail.tm account generation...
Retrying mail.tm account generation...
Registered account successfully!
Retrieved mail successfully!
Found mail!
Traceback (most recent call last):
  File "C:\Users\Dogan\Desktop\py_mega_account_generator-master\main.py", line 138, in <module>
    asyncio.run(register(asyncio.run(generate_mail())))
  File "C:\Users\Dogan\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Dogan\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\Dogan\Desktop\py_mega_account_generator-master\main.py", line 76, in register
    await initial_setup(context, message, credentials)
  File "C:\Users\Dogan\Desktop\py_mega_account_generator-master\utilities\web.py", line 43, in initial_setup
    await confirm_page.waitForSelector("#freeStart", timeout=1000)
  File "C:\Users\Dogan\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\frame_manager.py", line 855, in __await__
    raise result
pyppeteer.errors.TimeoutError: Waiting for selector "#freeStart" failed: timeout 1000ms exceeds.
```
Could it be because I use Brave browser or could it be because I uninstalled Edge?

**Comment by qtchaos** [comment]
Try going into task manager and stopping the browser process, if you have a `settings.json` file, then send a screenshot of it here.

**Comment by DogancanYr** [comment]
settings.json is not available anywhere, neither in the program nor in the browser. I also stopped all browser processes from the task manager.

**Comment by qtchaos** [comment]
Update to the newest version by either using `git pull` if you have git installed or download the repository again.

**Comment by DogancanYr** [comment]
All were up to date.

**Comment by DogancanYr** [comment]
Thanks for the correction, I'm trying it now.

**Comment by DogancanYr** [comment]
Thanks for the update. I'm trying it now.

**Comment by DogancanYr** [comment]
Nothing changed . 😭

**Comment by qtchaos** [comment]
I've tested this exact problem several times and this should have fixed it. I guess you can try using a different browser and then set up the `config.json` file as follows:

```
{"executablePath": "PATH_TO_CHROMIUM_EXEC\EXECUTABLE_NAME.exe"}
```

**Comment by DogancanYr** [comment]
I hope it works.I've been trying to do this for 5 hours.

**Comment by DogancanYr** [comment]
I couldn't understand exactly where config.json should be.

**Comment by DogancanYr** [comment]
I tried with Chrome and it still doesn't work.

**Comment by DogancanYr** [comment]
I also tried Microsoft, it didn't work.

**Comment by qtchaos** [comment]
This is very strange, I have handled the error properly in the code, and yet it's still popping up? Make sure that in the config.json file your path includes the .exe, with Edge it should end with `msedge.exe`, Chrome `chrome.exe` and so on.

**Comment by DogancanYr** [comment]
I did it right, still the same problem.

**Comment by DogancanYr** [comment]
I did it that way.

**Comment by DogancanYr** [comment]
I did it like you said.

**Comment by DogancanYr** [comment]
Can you do something with this program ? https://pypi.org/project/auto-py-to-exe/#description

**Comment by DogancanYr** [comment]
I tried to use it and it gives an error.

**Comment by qtchaos** [comment]
This wouldn't fix the problem. I'll work on packaging the script into an exe later once it's in a more stable state

**Comment by DogancanYr** [comment]
I tried it on another computer and got the same error again. 

Can you make a video of how you start it?
(From the beginning)

**Comment by xlly-s** [comment]
same issue here, have i got to make a config.json file btw?

**Comment by DogancanYr** [comment]
> same issue here, have i got to make a config.json file btw?

Creating the file doesn't change anything.

**Comment by xlly-s** [comment]
Haven't tried, however ive tried making the timeout longer, ill letr you know if it works.

**Comment by xlly-s** [comment]
Works! Go into web.py in services, then change the timeout from 1000 - 10000

**Comment by DogancanYr** [comment]
😍😍OwO😍😍

**Comment by qtchaos** [comment]
This might be an oversight on my part with internet speeds, the page should load within 10 seconds, but running on slower internet connections might take longer. Thanks for the PR @DogancanYr!

**Comment by DogancanYr** [comment]
Actually my internet is fast but I don't know why it's loading slowly .Then creates accounts quickly .

**Comment by qtchaos** [comment]
If you want you can edit your main.py and change the `headless` option to `False` and see if you can spot why this might happen :p

**Comment by DogancanYr** [comment]
Really nice settings. I didn't know such settings existed.
When I do it, it waits for a very short short time in the recovery key section.
