### ISSUE TITLE
Emails and passwords.

### ISSUE THREAD

**Issue by DogancanYr** [qtchaos/py_mega_account_generator#18]
Can emails and passwords be printed this way?

wasdwasd@wow.com#password1

**Comment by qtchaos** [comment]
I can try adding a custom format option for how to store passwords and emails, so that anyone can specify how they want them stored. I'll see if I can implement a clean solution soon.

**Comment by thejack99** [comment]
Can I re-use previous emails with storages left? Or can you add an upload option with automatic pickout the account with storage available.

**Comment by DogancanYr** [comment]
> Can I re-use previous emails with storages left? Or can you add an upload option with automatic pickout the account with storage available.

Get the accounts from here and upload them with this program. https://github.com/tonikelope/megadoctor

**Comment by qtchaos** [comment]
> Can I re-use previous emails with storages left? Or can you add an upload option with automatic pickout the account with storage available.

Any accounts you generate will be available for as long as mega doesnt take action against them (highly doubt they would). I believe you can use the `python main.py -ka -v` command, it'll login to all accounts and display how much storage is left aswell.

**Comment by thejack99** [comment]
I love #DogancanYr idea to print the email and password as Email#Pass and save to a text file

**Comment by qtchaos** [comment]
Added custom formats in https://github.com/qtchaos/py_mega_account_generator/commit/ea62c751dc5c36ae3121e88af5546a4367043df9, read the updated README.md to find out how to use this new feature.
