### ISSUE TITLE
No module named 'pyppeteer'

### ISSUE THREAD

**Issue by touhamii** [qtchaos/py_mega_account_generator#21]
Hi 
thank you for sharing with us this useful script 
i have python Python 3.10.11 installed on win10 64bit 
and i get this issue:  No module named 'pyppeteer'
https://i.imgur.com/Mf5FcL5.png
thank you for ur time

**Comment by qtchaos** [comment]
Try using the following command: `pip install -r requirements.txt`, then see if the same error occurs.

**Comment by touhamii** [comment]
i already used : pip install -r requirements.txt when installing and after i re used pip install -r requirements.txt it says that the script is there but after that it just worked .. weird 
one last question : is there a way to login to that email just to be sure that no one can acess to this email later espicially that it's a temporary email , also is there a difference between creating mega with a Gmail and with a temp email ? 
thank u

**Comment by qtchaos** [comment]
> is there a way to login to that email just to be sure that no one can acess to this email later espicially that it's a temporary email

You can go to https://mail.tm and login with the `email` and `emailPassword` credentials.  Nobody has access to your account except you.

>  is there a difference between creating mega with a Gmail and with a temp email ? 

No.
