### ISSUE TITLE
Failed to find a Chromium based browser. Please make sure you have one installed.

### ISSUE THREAD

**Issue by thejack99** [qtchaos/py_mega_account_generator#23]
I got error for new version 1.5.0
Failed to find a Chromium based browser. Please make sure you have one installed.
Please enter the path to a Chromium based browser's executable:

**Comment by qtchaos** [comment]
You have to paste a valid path to the chrome executable, for example: `C:/Users/Admin/Programs/Chrome/chrome.exe`
