### ISSUE TITLE
Can you adapt it for Mediafire?

### ISSUE THREAD

**Issue by DogancanYr** [qtchaos/py_mega_account_generator#24]
https://github.com/JayBrown/mfcmd.py---MediaFire-uploader

I opened 3 accounts and verified them with fake e-mails, one year ago.
Accounts can be verified through email inquiries.

https://www.mediafire.com/earnspace/ (Log in via mediafire to see the entire site.)  5=>50gb .

**Comment by qtchaos** [comment]
This doesn't really fit the scope of this project. But if i get some time and I feel like it, then I might create something new, sure.

**Comment by DogancanYr** [comment]
> This doesn't really fit the scope of this project. But if i get some time and I feel like it, then I might create something new, sure.

I meant creating a new project also mediafire offers high speed downloading and  files are never deleted. Much better than Mega.
