### ISSUE TITLE
How can i fix this error?

### ISSUE THREAD

**Issue by xjupx** [qtchaos/py_mega_account_generator#29]
![cmd_RwtKoBnHte](https://github.com/qtchaos/py_mega_account_generator/assets/157194734/302605c4-58c1-49a8-b6d3-464e18e5b938)

**Comment by qtchaos** [comment]
The browser executable is probably in an admin protected folder.

**Comment by PatreonOfficial** [comment]
Had the same issue, if you run on windows, you have to put "C:/Program Files/Google/Chrome/Application/chrome.exe" in the config.json as the browser path.
