### ISSUE TITLE
keep mega accounts alive

### ISSUE THREAD

**Issue by binnichtaktiv** [qtchaos/py_mega_account_generator#3]
Hi its me again :)
can you maybe add a option to log into your accounts so that they dont get deleted by mega? Because mega deletes accounts that are 3 months inactive. So can you maybe add a option that it can read the mail and pass from the credential folder so it can log into all of them if its possible and if you have time to do this?😁

**Comment by qtchaos** [comment]
Interesting... It's possible, yes. I'll try to implement this tonight.

**Comment by qtchaos** [comment]
Please refer to the README to learn how to use the keepalive function!

**Comment by binnichtaktiv** [comment]
> Please refer to the README to learn how to use the keepalive function!

thank you so much😍

**Comment by binnichtaktiv** [comment]
> Please refer to the README to learn how to use the keepalive function!

i get this when i run main.py

![image](https://user-images.githubusercontent.com/96953964/200134141-a9c27f22-ec24-4f6a-ab03-52ed784eb327.png)

i installed all requirements

**Comment by qtchaos** [comment]
Just noticed the issue and pushed a fix. If you don't want to redownload then just use `pip install mega.py`

**Comment by binnichtaktiv** [comment]
> Just noticed the issue and pushed a fix. If you don't want to redownload then just use `pip install mega.py`

its working perfectly now thank you so much
