### ISSUE TITLE
Failed to find mail... exiting

### ISSUE THREAD

**Issue by joethesaint** [qtchaos/py_mega_account_generator#33]
![image](https://github.com/qtchaos/py_mega_account_generator/assets/80671899/ee51bac5-5170-4313-9c08-e1b33a691b19)

Here is what I got. How do I go about it?

**Comment by qtchaos** [comment]
This should only happen if the mail.tm API is having a issues. If this only happened once, then this is not something I can fix.

**Comment by joethesaint** [comment]
I do not understand. Have you tried to replicate the error? Or is it a special one specifically for me? I currently assume it is a general issue. Please help me clarify

**Comment by qtchaos** [comment]
> I do not understand. Have you tried to replicate the error? Or is it a special one specifically for me? I currently assume it is a general issue. Please help me clarify

I haven't been able to replicate the error, the script runs fine for me. Seems to be something specific to you, does it still not work?
