### ISSUE TITLE
[WinError 193] 

### ISSUE THREAD

**Issue by Rosalyne0** [qtchaos/py_mega_account_generator#35]
![image](https://github.com/qtchaos/py_mega_account_generator/assets/138538014/d6c4203e-ab58-4aed-a2fc-7bdff826ac13)

I am aware this is likely a issue on my end but I'm stumped and need the help. I have no coding experience but usually manage fine figuring things out as I go and troubleshooting but this issue has me at a dead end, my only thought is maybe there's a issue with my environment and its unhappy becuase everything isn't on the same directory. I do also realize the problem is literally right in front of me in the traceback but I don't have the experience to make sense of it. any help would be awesome.

**The following is rambling and likely not relevant to the issue:**
but I have spent the last 6 hours setting up and learning how to use python and gitbash and troubleshooting various issues i ran into during the process, some caused by me being picky about where python and git got to put its files becuase i like my files to be organized and not just scattered all over in several directories like programs love doing so often, but im outa brain juice. git was originally in my users file but it was making a mess in there so i moved it to a local drive, I did this properly as far as im aware by changing git's home directory in the global config file and i was already having this issue before I did that anyway so i doubt that is the cause, i also tried modifying git to use python 310 instead of 312 but i couldn't get it working by messing with aliases and .bashrc and just gave up in favor of deleting 312 from my system to force it to use 310. just clarifying what custom changes i have made to git and python incase its relevant somehow to my problem but i doubt it. (while i was deleting 312 i also nuked pip by accident and had to manually reinstall that becuase the 310 installer didn't want to repair it for some reason. oops)

**Comment by qtchaos** [comment]
You're pointing the program to a `.link` file, not a `.exe`, which is required to run the program.
