### ISSUE TITLE
Browser closed unexpectedly

### ISSUE THREAD

**Issue by zdhd122a** [qtchaos/py_mega_account_generator#38]
already a year use your script, on windows, also on second boot ubuntu, now i try to install it on vds, Ubuntu 22.04.2 LTS base, and encounter error which not see before

> Traceback (most recent call last):
>   File "megupl/py_mega_account_generator/main.py", line 218, in <module>
>     asyncio.run(register(credentials, executable_path, config))
>   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
>     return future.result()
>   File "megupl/py_mega_account_generator/main.py", line 150, in register
>     browser = await pyppeteer.launch(
>   File "megupl/mainenv/lib/python3.10/site-packages/pyppeteer/launcher.py", line 307, in launch
>     return await Launcher(options, **kwargs).launch()
>   File "megupl/mainenv/lib/python3.10/site-packages/pyppeteer/launcher.py", line 168, in launch
>     self.browserWSEndpoint = get_ws_endpoint(self.url)
>   File "megupl/mainenv/lib/python3.10/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
>     raise BrowserError('Browser closed unexpectedly:\n')
> pyppeteer.errors.BrowserError: Browser closed unexpectedly:

i try to change browser nothing work, not chromium not chrome, not firefox
please help

**Comment by zdhd122a** [comment]
UPD. I installed the previous version, everything worked now
![image](https://github.com/user-attachments/assets/1df61f0c-7987-464a-be0b-fab539ec312e)

**Comment by qtchaos** [comment]
Interesting, I'll take a look.

**Comment by zdhd122a** [comment]
> There haven't been any changes to how we handle the browser between v1.5.1 and v1.5.0 so more information is needed either by you

sorry, i mean not previous version, not v1.5.0, i simply upload version from my pc to vds, so i'm not sure which version it is

**Comment by zdhd122a** [comment]
I think I've found the problem. on my version of ubuntu + xfce for some reason not works snaps, so firefox and chromium is snaps, if you have the same problem try to install something not from snap 
(for me
```
sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list'
sudo apt update
sudo apt install microsoft-edge-stable
```
works)

**Comment by qtchaos** [comment]
Ah i see, thanks for including how to fix it aswell, will surely be useful for others.
