### ISSUE TITLE
Failed to find mail

### ISSUE THREAD

**Issue by zdhd122a** [qtchaos/py_mega_account_generator#39]
![image](https://github.com/user-attachments/assets/b9bd857e-00ff-4a45-9231-0108fbeeea17)

this is again problem with mail.tm and we need only wait month or i can fix this? browsers with which i try to create mail - chromium, microsoft edge

**Comment by qtchaos** [comment]
Seems to be an issue with running the browser in headless mode, searching for the root issue atm.
