### ISSUE TITLE
module 'asyncio' has no attribute 'coroutine'

### ISSUE THREAD

**Issue by binnichtaktiv** [qtchaos/py_mega_account_generator#4]
Hi its me again
Is something wrong with my dependencies? Because it worked fine last time
![Bildschirm­foto 2022-12-11 um 13 25 08](https://user-images.githubusercontent.com/96953964/206903450-5350d2dd-5630-4729-9790-7984ee7933b9.jpg)

**Comment by qtchaos** [comment]
I believe this is an issue with the library I'm using to interact with the Mega.nz API.. not sure how to go about fixing this quite yet.

**Comment by binnichtaktiv** [comment]
> This is a problem with the library I'm using to interact with the mega.nz API. Since this library has not been maintained since 2020 it will show its age, I do not have the time to rewrite this library. I might see if I can fork it and maintain it, but no promises.

Hey 
did you maybe find something to fix this now?

**Comment by qtchaos** [comment]
> > This is a problem with the library I'm using to interact with the mega.nz API. Since this library has not been maintained since 2020 it will show its age, I do not have the time to rewrite this library. I might see if I can fork it and maintain it, but no promises.
> 
> Hey did you maybe find something to fix this now?

The only way for me to be able to support Python 3.11 is for me to fork the mega.nz API that I use, but I simply do not have the time especially because of exams to do that. There is a break coming up soon, so I might try to do something about it, but I don't suggest getting your hopes up.

**Comment by binnichtaktiv** [comment]
> After looking further into the issue, the issue was with a sub-dependency being severely outdated, I added a function to help fix this.

Thank you!
but now i get this😭 I have pyppeteer installed I checked it
![image](https://user-images.githubusercontent.com/96953964/220794486-bcbece79-1dfd-4116-b682-7446d73abaf3.png)

**Comment by binnichtaktiv** [comment]
here😅 everything is installed and working I checked 3 times now
https://gofile.io/d/YvN1iW

**Comment by qtchaos** [comment]
I wonder if maybe your pip is from a different version of Python? Run the `pip --version` and `python3 --version` commands to see if they are the same...

**Comment by binnichtaktiv** [comment]
> I wonder if maybe your pip is from a different version of Python? Run the `pip --version` and `python3 --version` commands to see if they are the same...

oh they are not... how can i fix this? cant find a solution online only long documentations

**Comment by binnichtaktiv** [comment]
> I believe you can use `python3 -m pip` instead of `pip`. You can also try seeing if the `pip3` command works?

i fixed it with `python3 -m pip install -r requirements.txt`

**Comment by binnichtaktiv** [comment]
bruh now i get this😭 tried 2 times and this happens
![image](https://user-images.githubusercontent.com/96953964/221269110-867bb841-aa59-4771-8b7a-971b1d346b3b.png)

**Comment by qtchaos** [comment]
I'm getting similar results, this is most likely an issue with the mail.tm API being slow, there is nothing I can do to help fix this 🙁

**Comment by binnichtaktiv** [comment]
> I'm getting similar results, this is most likely an issue with the mail.tm API being slow, there is nothing I can do to help fix this 🙁

oh okay :( so it doesn't work at all or do you just have to wait?
