### ISSUE TITLE
Requesting new features

### ISSUE THREAD

**Issue by Robiftp** [qtchaos/py_mega_account_generator#6]
It would be nice if you added an option to loop the account creation so you would be able to make a lot of accounts without having to type every time "python main.py". Also a proxy feature would be nice so the accounts would come from a different ip address.

**Comment by qtchaos** [comment]
Sorry for the late response, a loop option is a good idea yes, the proxy would be pretty annoying to implement but I'll see if I can be bothered. :P

**Comment by awdwadwadwad12345** [comment]
> Sorry for the late response, a loop option is a good idea yes, the proxy would be pretty annoying to implement but I'll see if I can be bothered. :P

plz proxy

**Comment by qtchaos** [comment]
> It would be nice if you added an option to loop the account creation so you would be able to make a lot of accounts without having to type every time "python main.py". Also a proxy feature would be nice so the accounts would come from a different ip address.

Added looping in fd13bf23753b15a419db6970de9228a6a5b6b895. The proxying bit is as i can see, very hard or impossible to do with pure Python without moving all of the system traffic to the proxy, which you can do yourself anyways.
