### ISSUE TITLE
need help with file storage and keep alive features

### ISSUE THREAD

**Issue by test63464** [qtchaos/py_mega_account_generator#7]
hello. Thank you for this awesome generator. Though I can't login into accounts(screenshot shared). 

Also I need to know I have many Generated mega accounts which just have their Login Email And Password, so is there any ways I can put them into .json files and login through your tool. Appreciate your work. 

Hoping for a reply soon.
Thank you.
![111111](https://user-images.githubusercontent.com/126057282/228351650-8933d539-2626-48ea-adf2-8a3587f0da3f.png)

**Comment by qtchaos** [comment]
hey the problem here is that you are not executing the python application. use something like this `python main.py <argument>`
