### ISSUE TITLE
[Request] a way to not only use chrome

### ISSUE THREAD

**Issue by binnichtaktiv** [qtchaos/py_mega_account_generator#9]
Hi
The new update works great👍🏻 I just wanted to ask if it's possible to use more than just chrome. I had to download it specifically for this. I have brave and edge. Maybe it's possible that I can choose one of them instead of installing Chrome specifically for it. 

Thanks for the updates and the good work

**Comment by qtchaos** [comment]
Any Chromium based browser should work, I'll create a commit to reflect this in the text.

**Comment by binnichtaktiv** [comment]
> Any Chromium based browser should work, I'll create a commit to reflect this in the text.

Works now👍🏻
But I get this do you know why
![image](https://github.com/qtchaos/py_mega_account_generator/assets/96953964/5a32dcee-6151-4937-b0cc-bea910827839)

**Comment by qtchaos** [comment]
> > Any Chromium based browser should work, I'll create a commit to reflect this in the text.
> 
> Works now👍🏻 But I get this do you know why ![image](https://user-images.githubusercontent.com/96953964/270639299-5a32dcee-6151-4937-b0cc-bea910827839.png)

Keep trying, works for me. If the error still occurs then comment here again.
